version: '3'
services:

  #PHP Service
  app:
    image: cheanizer/php74-laravel
    container_name: poc
    restart: unless-stopped
    tty: true
    build :
      context : ./docker/php/
      dockerfile : Dockerfile
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - dock-net

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "8080:80"
      #- "443:443"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - dock-net

  #MySQL Service
  db:
    image: mysql:5.7.22
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3006:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: jamansudahberubah
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - C:\mysql\dbnull:/var/lib/mysql/
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - dock-net
#Docker Networks
networks:
  dock-net:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local
